In [1]:
import numpy as np

## 3 im2col関数(行方向の繰り返し)

In [2]:
def im2col(x, fil_size, y_size, stride, pad):
    x_b, x_c, x_h, x_w = x.shape
    fil_h, fil_w = fil_size, fil_size
    y_h, y_w = y_size, y_size
    index = -1
    
    x_pad = np.pad(x, [(0, 0), (0, 0), (pad, pad), (pad, pad)], "constant")
    x_col = np.zeros((fil_h*fil_w, x_b, x_c, y_h, y_w))
    
    for h in range(fil_h):
        h2 = h + y_h*stride
        for w in range(fil_w):
            index += 1
            w2 = w + y_w*stride
            x_col[index,:,:,:,:] = x_pad[:,:,h:h2:stride,w:w2:stride]
    x_col = x_col.transpose(2,0,1,3,4).reshape(x_c*fil_h*fil_w, x_b*y_h*y_w)
    
    return x_col

## 3.1 バッチサイズ1

In [3]:
x = np.arange(48).reshape(1,3,4,4)
print(x)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]
   [12 13 14 15]]

  [[16 17 18 19]
   [20 21 22 23]
   [24 25 26 27]
   [28 29 30 31]]

  [[32 33 34 35]
   [36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]


In [4]:
x1 = im2col(x,3,2,1,0)
print(x1)

[[ 0.  1.  4.  5.]
 [ 1.  2.  5.  6.]
 [ 2.  3.  6.  7.]
 [ 4.  5.  8.  9.]
 [ 5.  6.  9. 10.]
 [ 6.  7. 10. 11.]
 [ 8.  9. 12. 13.]
 [ 9. 10. 13. 14.]
 [10. 11. 14. 15.]
 [16. 17. 20. 21.]
 [17. 18. 21. 22.]
 [18. 19. 22. 23.]
 [20. 21. 24. 25.]
 [21. 22. 25. 26.]
 [22. 23. 26. 27.]
 [24. 25. 28. 29.]
 [25. 26. 29. 30.]
 [26. 27. 30. 31.]
 [32. 33. 36. 37.]
 [33. 34. 37. 38.]
 [34. 35. 38. 39.]
 [36. 37. 40. 41.]
 [37. 38. 41. 42.]
 [38. 39. 42. 43.]
 [40. 41. 44. 45.]
 [41. 42. 45. 46.]
 [42. 43. 46. 47.]]


## 3.1 バッチサイズ3

In [5]:
x = np.arange(144).reshape(3,3,4,4)
print(x)

[[[[  0   1   2   3]
   [  4   5   6   7]
   [  8   9  10  11]
   [ 12  13  14  15]]

  [[ 16  17  18  19]
   [ 20  21  22  23]
   [ 24  25  26  27]
   [ 28  29  30  31]]

  [[ 32  33  34  35]
   [ 36  37  38  39]
   [ 40  41  42  43]
   [ 44  45  46  47]]]


 [[[ 48  49  50  51]
   [ 52  53  54  55]
   [ 56  57  58  59]
   [ 60  61  62  63]]

  [[ 64  65  66  67]
   [ 68  69  70  71]
   [ 72  73  74  75]
   [ 76  77  78  79]]

  [[ 80  81  82  83]
   [ 84  85  86  87]
   [ 88  89  90  91]
   [ 92  93  94  95]]]


 [[[ 96  97  98  99]
   [100 101 102 103]
   [104 105 106 107]
   [108 109 110 111]]

  [[112 113 114 115]
   [116 117 118 119]
   [120 121 122 123]
   [124 125 126 127]]

  [[128 129 130 131]
   [132 133 134 135]
   [136 137 138 139]
   [140 141 142 143]]]]


In [6]:
x2 = im2col(x,3,2,1,0)
print(x2)

[[  0.   1.   4.   5.  48.  49.  52.  53.  96.  97. 100. 101.]
 [  1.   2.   5.   6.  49.  50.  53.  54.  97.  98. 101. 102.]
 [  2.   3.   6.   7.  50.  51.  54.  55.  98.  99. 102. 103.]
 [  4.   5.   8.   9.  52.  53.  56.  57. 100. 101. 104. 105.]
 [  5.   6.   9.  10.  53.  54.  57.  58. 101. 102. 105. 106.]
 [  6.   7.  10.  11.  54.  55.  58.  59. 102. 103. 106. 107.]
 [  8.   9.  12.  13.  56.  57.  60.  61. 104. 105. 108. 109.]
 [  9.  10.  13.  14.  57.  58.  61.  62. 105. 106. 109. 110.]
 [ 10.  11.  14.  15.  58.  59.  62.  63. 106. 107. 110. 111.]
 [ 16.  17.  20.  21.  64.  65.  68.  69. 112. 113. 116. 117.]
 [ 17.  18.  21.  22.  65.  66.  69.  70. 113. 114. 117. 118.]
 [ 18.  19.  22.  23.  66.  67.  70.  71. 114. 115. 118. 119.]
 [ 20.  21.  24.  25.  68.  69.  72.  73. 116. 117. 120. 121.]
 [ 21.  22.  25.  26.  69.  70.  73.  74. 117. 118. 121. 122.]
 [ 22.  23.  26.  27.  70.  71.  74.  75. 118. 119. 122. 123.]
 [ 24.  25.  28.  29.  72.  73.  76.  77. 120. 121. 124